version: "3.3"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=basepassword
      - MYSQL_ROOT_PASSWORD=rootpassword

    ports:
      - "3306:3306"
    networks:
      - local
    volumes:
      - availityData:/Code/poc/availity/sql/data

networks:
  local:
    driver: bridge

volumes:
  availityData:
    external: true
